# first, install Cypress, then run all tests (in parallel)
image: registry.gitlab.com/william.ralitera/formation:latest

stages:
  - TEST

TEST:
  stage: TEST
  before_script:
    - rm -rf cypress/integration/tests/**/**
    - rm -rf multiple-results/*
    - hiptest-publisher --verbose -c hiptest-publisher.conf --without=actionwords --test-run-name $TEST_RUN_NAME
  script:
    - rm -rf node_modules
    - rm package-lock.json
    - npm cache clear --force
    - npm install
    - echo $BASE_URL
    - export CYPRESS_BASE_URL=$BASE_URL
    #Print console.log to Terminal
    - export ELECTRON_ENABLE_LOGGING=true
    - npx cypress run --reporter mocha-multi-reporters --reporter-options configFile=config.json --spec 'cypress/integration/tests/**/**' --env configFile=localhost
  after_script:
    - npx mochawesome-merge --reportDir multiple-results/results > mochawesome.json || true
    - npx mochawesome-report-generator mochawesome.json || true
    - hiptest-publisher --verbose -c hiptest-publisher.conf --push="./multiple-results/*.xml" --test-run-name $TEST_RUN_NAME --push-format=junit || true
  artifacts:
    reports:
      junit: ./multiple-results/*.xml
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
      - cypress/integration
      - mochawesome-report
      - multiple-results
      - mochawesome.json
    expire_in: 1 week
  allow_failure: true
