# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  CypressTest:
    docker:
      - image: bentrole/personal:ruby-hiptest-chrome-cypress-pack
    steps:
      - checkout
      - run: rm -rf cypress/integration/tests/**/**
      - run: rm -rf multiple-results/*
      - run:
          name: "Get scenarios to test on CucumberStudio"
          command: hiptest-publisher --verbose -c hiptest-publisher.conf --without=actionwords --test-run-name $TEST_RUN_NAME
      - run: npm cache clear --force
      - run: npm install
      - run: export CYPRESS_BASE_URL=$BASE_URL
      - run: echo ${BASE_URL}
      - run: echo ${TEST_RUN_NAME}
      - run: export ELECTRON_ENABLE_LOGGING=true
      - run:
          name: "Run Cypress Tests"
          command: CYPRESS_BASE_URL=$BASE_URL npx cypress run --reporter mocha-multi-reporters --reporter-options configFile=config.json --spec 'cypress/integration/tests/**/**' --env configFile=localhost
      #- run: npx cypress run --reporter mocha-multi-reporters --reporter-options configFile=config.json --spec 'cypress/integration/tests/**/**' --env configFile=localhost
      - run: hiptest-publisher --verbose -c hiptest-publisher.conf --push="./multiple-results/*.xml" --test-run-name $TEST_RUN_NAME --push-format=junit || true
      - run: npx mochawesome-merge --reportDir multiple-results/results > mochawesome.json || true
      - run: npx mochawesome-report-generator mochawesome.json || true
      - run: 
          name: "Merge junit xml to json file"
          command: npx mochawesome-merge --reportDir multiple-results/results > mochawesome.json
      - run:
          name: "Generate a single HTML Report"
          command: npx mochawesome-report-generator mochawesome.json
      - run:
          name: "Send Report To CucumberStudio"
          command: hiptest-publisher --verbose -c hiptest-publisher.conf --push="./multiple-results/*.xml" --test-run-name $TEST_RUN_NAME --push-format=junit
      - store_test_results:
          path: multiple-results/
      - store_artifacts:
          path: mochawesome-report
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/integration
workflows:
  version: 2
  Test:
    jobs:
      - CypressTest:
          context: Environment
